# -*- coding: utf-8 -*-
"""Conversion table.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mHj_3SSQml_dHV7VDkin9kSJ6NS6N-bi
"""

print('F C')
C = 0 #initially celcius =0
while C <= 250: #we are taking only till 250 degrees
  F = 9 * C / 5 + 32 # conversion formula for celcius to farhenheit
  print(F, C)
  C += 10 #we increase by 10 in each step

print(' F C')
C = 0
while C <= 250:
  F = 9 * C / 5 + 32
  print('%4.0f %4.0f' % (F, C)) # formatting output with 4 field width and with 0 decimals
  C += 10

print(' F C')
for C in range(0, 250, 10): # using for lop for a set with set having multiples of 10 from 0 to 250
  F = 9 * C / 5 + 32
  print('%4.0f %4.0f' % (F, C))

print(' F C')
for C in range(-50, 50, 5):
  F = 9 * C / 5 + 32
  print('%4.0f %4.0f' % (F, C))

Cs = [0, 10] # create list using []
Cs.append(20) # modify by appending an entry
Cs

Cs = (0, 10) # create a tuple using ()

Cs = [] # empty list
Fs = []
for C in range(0, 250, 25):
  Cs.append(C) # appending celcius vallues to empty list Cs
  Fs.append(9 * C / 5 + 32) # appending corresponding farhenheit value to another list named Fs

print(Cs) #printing celcius array

print(Fs) # Printing farhenheit array

print(' F C')
for C, F in zip(Cs, Fs): #zip allows to traverse two lists simultaneously
  print('%4.0f %4.0f' % (F, C))

Fs = [9 * C / 5 + 32 for C in Cs] # we can do operations on elememts of a list if needed

Fs