# -*- coding: utf-8 -*-
"""Interacting with python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ATqB6hJMHjOdpV3dHba0-7UoCKhlVkfW
"""

from math import cos, sqrt, pi
cos(pi*sqrt(pi))**7
#math module contains different math functions such as sine and cosine

from math import cos, sqrt, pi
print('Hello, I can compute! ')
x = 3
y = cos(pi*sqrt(pi)*x)**7
print('Starting from x =', x, 'we have computed y=', y)
#we assign seperate values for x and y and use it later

