# -*- coding: utf-8 -*-
"""Power Sum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IxeusbfI_1bRFsA7vG48ngNaXW35jO8c
"""

N=int(input("Please Enter integer  N: ")) #input an integer for N
i=int(input("Please Enter integer i: ")) #input an integer for i
sum=0 #initial sum =0
for k in range(1,N+1): # taking set 1,2,...N
  sum+=k**i #sum=sum+k**i
print(sum) #printing final values