# -*- coding: utf-8 -*-
"""working with git

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zsui-N2YI_3ljGRTEZWfo-ewxdaOHSo_
"""

from git import Repo
#importing class repo from git module

help(Repo.clone_from)
#class documentation

help(Repo.__init__)

coursefolder = '/Users/Jay/tmpdir/'
#Course repository

import os
os.path.abspath(coursefolder)
#making a local copy

repodir = os.path.join(os.path.abspath(coursefolder), 'mth271content')
repodir # full path name of the subfolder

os.path.isdir(repodir)
#in first run it was false,after running once it became true

if os.path.isdir(repodir): # if repo exists, pull newest data
  repo = Repo(repodir)
  repo.remotes.origin.pull()
else: # otherwise, clone from remote
  repo = Repo.clone_from('https://github.com/jayggg/mth271content' ,repodir)
#Repo object was either initialized with repodir (if that folder exists) or set to clone a remote repository at a URL.

repo.working_dir